/**
 * Every guide page is meant to carry its own social card.
 *
 * The cards are generated by scripts/generate-og-images.mjs and listed in the
 * generated og-manifest.ts, so a page added without re-running the generator
 * would silently fall back to the one generic og-image.png — invisible in
 * review, and obvious the first time someone pastes the link anywhere. These
 * tests tie the two together at the source; check-seo.mjs re-checks the truth
 * against the built HTML.
 */

import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  OG_CIRCUITS_MANIFEST,
  OG_COMPONENTS_MANIFEST,
  OG_SECTIONS_MANIFEST,
  OG_TOOLS_MANIFEST,
  ogCardUrl,
} from '../og-manifest';

/* Resolved from the repo root, the same convention guide.test.ts uses. */
const CONTENT_ROOT = resolve(process.cwd(), 'astro-site/src/content');

function slugsIn(directory: string): string[] {
  const dir = resolve(CONTENT_ROOT, directory);
  return readdirSync(dir)
    .filter((file) => file.endsWith('.json'))
    .map((file) => JSON.parse(readFileSync(`${dir}/${file}`, 'utf8')).slug as string);
}

function circuitIds(): string[] {
  const guide = JSON.parse(readFileSync(resolve(CONTENT_ROOT, 'pages/guide.json'), 'utf8')) as {
    circuits: { id: string }[];
  };
  return guide.circuits.map((circuit) => circuit.id);
}

/** The guide landing pages: the hub, four section indexes and the glossary. */
const SECTION_PAGES = ['guide', 'components', 'tools', 'circuits', 'templates', 'glossary'];

describe('OG card coverage', () => {
  it('has a card for every component', () => {
    const slugs = slugsIn('guide-components');
    expect(slugs.length).toBeGreaterThan(0);
    expect(Object.keys(OG_COMPONENTS_MANIFEST).sort()).toEqual([...slugs].sort());
  });

  it('has a card for every tool', () => {
    const slugs = slugsIn('guide-tools');
    expect(slugs.length).toBeGreaterThan(0);
    expect(Object.keys(OG_TOOLS_MANIFEST).sort()).toEqual([...slugs].sort());
  });

  it('has a card for every circuit', () => {
    expect(Object.keys(OG_CIRCUITS_MANIFEST).sort()).toEqual([...circuitIds()].sort());
  });

  it('has a card for every guide landing page', () => {
    expect(Object.keys(OG_SECTIONS_MANIFEST).sort()).toEqual([...SECTION_PAGES].sort());
  });

  it('gives every card its own content hash', () => {
    for (const manifest of [
      OG_COMPONENTS_MANIFEST,
      OG_TOOLS_MANIFEST,
      OG_CIRCUITS_MANIFEST,
      OG_SECTIONS_MANIFEST,
    ]) {
      const hashes = Object.values(manifest);
      expect(hashes.every((hash) => /^[0-9a-f]{10}$/.test(hash))).toBe(true);
      expect(new Set(hashes).size).toBe(hashes.length);
    }
  });
});

describe('ogCardUrl', () => {
  it('builds the path and cache-busting query for a guide card', () => {
    expect(ogCardUrl('mcb', 'components')).toBe(
      `/og/guide/components/mcb.png?v=${OG_COMPONENTS_MANIFEST.mcb}`,
    );
    expect(ogCardUrl('circuit-9', 'circuits')).toBe(
      `/og/guide/circuits/circuit-9.png?v=${OG_CIRCUITS_MANIFEST['circuit-9']}`,
    );
    expect(ogCardUrl('glossary', 'sections')).toBe(
      `/og/guide/glossary.png?v=${OG_SECTIONS_MANIFEST.glossary}`,
    );
  });

  it('keeps the blog and changelog paths it shipped with', () => {
    expect(ogCardUrl('what-is-an-mcb-breaker')).toMatch(
      /^\/og\/blog\/what-is-an-mcb-breaker\.png\?v=/,
    );
    expect(ogCardUrl('electrasim-2-0-release', 'updates')).toMatch(
      /^\/og\/updates\/electrasim-2-0-release\.png\?v=/,
    );
  });
});
