/** Reviewed, explicit catalogue inventory. New variants must be classified here.
 * Neither a type substring nor a power label defines a source or load law.
 */
export const CAPABILITY_CATALOGUE_VERSION = '1.5d.0.1' as const;

const FAMILIES = {
  'resistive-load': [
    'space-heater',
    'water-heater',
    'electric-shower',
    'immersion-heater',
    'underfloor-heating',
    'storage-heater',
    'heating-element',
    'bulb-incandescent',
    'bulb-halogen',
  ],
  'mains-electronic-load': ['bulb', 'bulb-cfl', 'bulb-smart-rgb', 'led-downlight', 'tube-light'],
  'motor-load': [
    'ceiling-fan',
    'extractor-fan',
    'industrial-exhaust-fan',
    'table-fan',
    'motor',
    'water-pump',
  ],
  'unknown-load': [
    'bell',
    'air-conditioner',
    'induction-hob',
    'ev-charger',
    'extractor-hood',
    'heat-pump',
    'dishwasher',
    'washing-machine',
    'tumble-dryer',
    'fridge-freezer',
    'electric-buzzer',
    'wireless-doorbell',
    'alarm-siren',
    'smoke-alarm',
    'burglar-alarm',
  ],
  'three-phase-load': ['motor-3phase'],
  'manual-contact': [
    'single-way-switch',
    'two-way-switch',
    'intermediate-switch',
    'double-pole-switch',
    'push-button',
    'rotary-selector-switch',
    'contactor',
    'cooker-unit',
    'double-gang-switch',
    'contactor-2p',
    'contactor-3p',
    'contactor-4p',
    'thermostat',
    'room-thermostat',
    'door-sensor',
  ],
  'controlled-contact': [
    'fan-dimmer',
    'dimmer-switch',
    'pir-sensor',
    'photocell-sensor',
    'smart-relay',
    'timer-switch',
    'digital-weekly-timer',
    'staircase-timer',
    'countdown-timer',
    'heating-thermostat',
  ],
  'coil-contact': [
    'delay-timer',
    'relay-spst',
    'relay-spdt',
    'relay-dpdt',
    'control-relay',
    'contactor-1p',
  ],
  protection: [
    'mcb',
    'mcb-type-c',
    'mcb-type-d',
    'mccb',
    'rcd',
    'rcbo',
    'afdd',
    'fuse',
    'main-switch',
    'fused-spur',
    'isolator-switch',
  ],
  outlet: [
    'socket-2pin',
    'socket-3pin',
    'double-socket',
    'socket-usb',
    'socket-gfci',
    'socket-industrial',
    'socket-us',
    'double-socket-us',
    'socket-schuko',
    'socket-schuko-double',
    'socket-as3112',
    'socket-as3112-double',
    'socket-bs546',
    'shaver-socket',
    'socket-bs546-double',
    'switched-socket',
  ],
  source: ['ac-mains-supply', 'diesel-generator', 'dc-battery-12v', 'solar-pv-panel'],
  'source-alias': ['live-terminal', 'neutral-terminal'],
  'pe-reference': ['earth-terminal', 'earth-rod'],
  connection: [
    'kwh-meter',
    'junction-box',
    'terminal-strip',
    'wago-connector',
    'distribution-board',
    'distribution-box',
    'distribution-board-3phase',
  ],
  transformer: ['transformer-8v', 'transformer-12v', 'transformer-24v', 'step-up-down-transformer'],
  unassessed: ['spd', 'temperature-sensor'],
} as const;

export type CapabilityFamily = keyof typeof FAMILIES;
export const DEVICE_CAPABILITY_FAMILIES: Readonly<Record<string, CapabilityFamily>> = Object.freeze(
  Object.fromEntries(
    Object.entries(FAMILIES).flatMap(([family, types]) => types.map((type) => [type, family])),
  ) as Record<string, CapabilityFamily>,
);

/** Versioned teaching assumption for the existing element/hot-filament models.
 * This describes the modeled element, not an appliance controller or a damage limit.
 */
export const RESISTIVE_NOMINAL_VOLTS = 230;
